spring:
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:notes_db
    username: user
  sql:
    init:
      data-locations: classpath:notes.sql
      mode: always
  h2:
    console:
      enabled: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true